#!/usr/bin/env bash
# This script configures a new nginx web server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > sudo tee /var/www/html/index.html
sudo service nginx restart
