#!/usr/bin/env bash
# This script configures a new nginx web server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo 'location redirect_me/ {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }' >> sudo tee /etc/nginx/site-available/default

sudo service nginx restart
