#!/usr/bin/env bash
# This script configures a new nginx web server
str1='listen \[::\]:80 default_server;'
str2='listen \[::\]:80 default_server;\
	     location /redirect_me {\
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
	}'
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s|${str1}|${str2}|" /etc/nginx/sites-enabled/default
sudo service nginx start
