#!/usr/bin/env bash
# This script configures a new nginx web server

sudo apt-get update
sudo apt-get -y install nginx
# echo "Hello World!" | sudo tee /var/www/html/index.html
# echo 'location redirect_me/ {
#     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
#     }' >> sudo tee /etc/nginx/site-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i 's|try_files \$uri \$uri/ =404;|try_files \$uri \$uri/ =404;\
     	 error_page 404 /404.html;\
	 location = /404.html {\
	 root /usr/share/nginx/html;\
	 internal;\
}|' /etc/nginx/sites-enabled/default
service nginx restart
