#!/usr/bin/env bash
# This script configures a new nginx web server

# str1='listen \[::\]:80 default_server;'
# str2='listen \[::\]:80 default_server;\n\tlocation \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/watch\?v\=QH2-TGUlwu4;\n\t}'
sudo apt-get update
sudo apt-get -y install nginx

# echo "Hello World!" | sudo tee /var/www/html/index.html
# sudo sed -i "s|${str1}|${str2}|" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i 's|try_files \$uri \$uri/ =404;|try_files \$uri \$uri/ =404;\
     	 error_page 404 /404.html;\
	 location = /404.html {\
	 root /usr/share/nginx/html;\
	 internal;\
}|' /etc/nginx/sites-enabled/default

sudo service nginx start
