#!/usr/bin/env bash
# This script configures a new nginx web server

sudo apt-get update
sudo apt-get -y install nginx
# echo "Hello World!" | sudo tee /var/www/html/index.html
# echo 'location redirect_me/ {
#     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
#     }' >> sudo tee /etc/nginx/site-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i s|"=404;"|"=404;\
error_page 404 /404.html;\
location = /404.html {\
root /usr/share/nginx/html;\
internal;\
" /etc/nginx/site-enabled/default
sudo service nginx restart
