#!/usr/bin/env bash
# This script installs a load balancer in a new server

sudo apt-get -y update
sudo apt-get -y install haproxy
echo 'ENABLED=1' >> sudo tee /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.original}

echo 'frontend http
     	       bind *:80
	       default_backend web_backend

backend web_backend
     	      balance roundrobin
	      server 345282-web-01 52.3.242.181
	      server 345282-web-02 54.160.89.117' | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
