#!/usr/bin/env bash
# This script creates a MYSQL dump and creates a compressed archive out of it

filename=$(date +%d-%m-%Y)
ext=".tar.gz"
filename="$filename$ext"

mysqldump -u root -p"$1" --all-databases | sudo tee backup.sql
tar -czvf "$filename" backup.sql
