#!/usr/bin/env bash
# This script checks if Nginx is running on port 80
sed -i '0,/8080/s//80/' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx start
