#!/usr/bin/env bash
# This is an init script that manages the manage_my_process program

arg1="start"
arg2="stop"
arg3="restart"

if [ $# -ne 1 ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
else
    case "$1" in
	"$arg1")
	    ./manage_my_process &
	    echo "$!" >  /var/run/my_process.pid
	    echo "manage_my_process started"
	    ;;
	"$arg2")
	    pkill -f "./manage_my_process"
	    rm /var/run/my_process.pid
	    echo "manage_my_process stopped"
	    ;;
	"$arg3")
	    pkill -f "./manage_my_process"
	    rm /var/run/my_process.pid
	    ./manage_my_process &
            echo "$!" >  /var/run/my_process.pid
	    echo "manage_my_process restarted"
	    ;;
	*)
	    echo "Usage: manage_my_process {start|stop|restart}"
	    ;;
    esac
fi
