#!/usr/bin/env bash
# The script uses the content of the /etc/passwd
#+ to tell a story


while IFS=":" read -r USER PASS USER_ID GID UsID HOME_DIR COMMAND
do
    echo "The user $USER is part of the $GID gang, lives in $HOME_DIR and rides $COMMAND. $USER_ID's place is protected by the passcode $PASS, more info about the user here: $UsID"
done < /etc/passwd
