#!/usr/bin/env bash
# This script prints "Best School" all the time, but "Hi' on the 9th.

count=11
string="Best School"
string1="Hi"
while [ $count -ge 1 ]; do
    if [ $count -eq 2 ]; then
	echo "$string1"
    else
	echo "$string"
    fi
    (( count--))
done
