#!/usr/bin/env bash
# This script configures nginx to run as non-root
chmod 644 /etc/nginx/nginx.conf
service nginx stop
sed -i 's|^user .*;$|user nginx;|g' /etc/nginx/nginx.conf
sed -i 's|80|8080|g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
